# -*- coding: utf-8 -*-
"""Rock Paper Scisssors Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlYStNisWk6h-av9yJqn9tyUlaWjtsN8

# Rock, Paper, Scissors Game

This notebook implements a simple, interactive **Rock, Paper, Scissors** game in Python.

### How it works:
1. **Define Options:** The game supports three moves: Rock, Paper, and Scissors.
2. **User Input:** The player is prompted to enter their choice.
3. **Computer Opponent:** The computer randomly selects one of the three options.
4. **Winner Determination:** The game compares both choices according to standard rules to decide the winner, loser, or if it is a tie.

### 1. Define the Game Options
First, we import the `random` library and define our standard list of options: Rock, Paper, and Scissors.
"""

import random

"""### 2. Get User Input
We prompt the user to input their choice and normalize it to lowercase to avoid case-sensitivity issues.
"""

choices = ["rock", "paper", "scissors"]
user_choice = input (" choose rock, paper, Or Scissors: ").lower()

"""### 3. Validate Input & Generate Computer Choice
We check if the user entered a valid choice. If valid, we generate a random choice for the computer and display both selections.
"""

import sys

if user_choice not in choices:
    print("Invalid choice. Please choose either rock, paper, or scissors.")
else:
    # Generate a random choice for the computer
    computer_choice = random.choice(choices)
    # Display selections
    print(f"You chose: {user_choice.capitalize()}")
    print(f"Computer chose: {computer_choice.capitalize()}")

"""## 4. Determine the winner"""

# 4. Determine the winner
# Check if the computer has made a choice and the user's choice is valid
if 'computer_choice' in locals() and user_choice in choices:
    # If both chose the same option, it is a tie
    if user_choice == computer_choice:
        print("\nResult: It's a tie!")
    # Check all winning conditions for the user
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        print("\nResult: You win!")
    # If it is not a tie and the user didn't win, then the computer wins
    else:
        print("\nResult: You lose!")
else:
    print("\nGame could not be played due to an invalid user choice.")